In [1]:
import os

In [10]:
path = "C:/Users/Playdata/Desktop/Save-Pets-ML-main/SVM-Classifier/Dog-Data/train"
file_list = os.listdir(path)

In [11]:
print(file_list)

['0', '1', '2', '3', '4', '5']


In [12]:
for i, label in enumerate(file_list):
    print(label)

0
1
2
3
4
5


In [13]:
label2id = {}
idx = 0
for i, label in enumerate(file_list):
    if label == ".DS_Store": 
        continue;
    # If the label is not ".DS_Store," 
    # a numerical identifier idx is assigned to that label,
    # and the label-ID mapping is stored in the label2id dictionary.
    label2id[label] = idx
    idx += 1


In [14]:
label2id

{'0': 0, '1': 1, '2': 2, '3': 3, '4': 4, '5': 5}

In [15]:
for label in os.listdir('../SVM-Classifier/Dog-Data/train/'):
    print(label)
    if os.path.isdir(os.path.join('../SVM-Classifier/Dog-Data/train/', label)):
        print(os.path.join('../SVM-Classifier/Dog-Data/train/', label))
        for img_file in os.listdir(os.path.join('../SVM-Classifier/Dog-Data/train', label)):
            print(img_file)
            #img = cv2.imread(os.path.join('./SVM-Classifier/Dog-Data/train', label, img_file))

0
../SVM-Classifier/Dog-Data/train/0
cut_20201001_153748-0.jpg
cut_20201001_153748-1.jpg
cut_20201001_153748-2.jpg
cut_20201001_153748-3.jpg
cut_20201001_153748-4.jpg
cut_20201001_153748-5.jpg
cut_20201001_153748-6.jpg
cut_20201001_153748-7.jpg
cut_20201001_153748-8.jpg
cut_20201001_153748-9.jpg
cut_20201001_153752-0.jpg
cut_20201001_153752-1.jpg
cut_20201001_153752-2.jpg
cut_20201001_153752-3.jpg
cut_20201001_153752-4.jpg
cut_20201001_153752-5.jpg
cut_20201001_153752-6.jpg
cut_20201001_153752-7.jpg
cut_20201001_153752-8.jpg
cut_20201001_153752-9.jpg
cut_20201001_153753-0.jpg
cut_20201001_153753-1.jpg
cut_20201001_153753-2.jpg
cut_20201001_153753-3.jpg
cut_20201001_153753-4.jpg
cut_20201001_153753-5.jpg
cut_20201001_153753-6.jpg
cut_20201001_153753-7.jpg
cut_20201001_153753-8.jpg
cut_20201001_153753-9.jpg
cut_20201001_153755-0.jpg
cut_20201001_153755-1.jpg
cut_20201001_153755-2.jpg
cut_20201001_153755-3.jpg
cut_20201001_153755-4.jpg
cut_20201001_153755-5.jpg
cut_20201001_153755-6.jpg
c

In [16]:
import cv2
cv2.imread('../SVM-Classifier/Dog-Data/train/0/cut_20201001_153748-0.jpg')

array([[[ 56,  75,  88],
        [ 69,  88, 101],
        [ 75,  92, 105],
        ...,
        [214, 240, 254],
        [200, 223, 239],
        [190, 213, 229]],

       [[ 55,  74,  87],
        [ 62,  81,  94],
        [ 70,  87, 100],
        ...,
        [213, 236, 251],
        [199, 222, 237],
        [191, 214, 229]],

       [[ 52,  69,  82],
        [ 55,  72,  85],
        [ 66,  83,  96],
        ...,
        [206, 228, 240],
        [200, 222, 234],
        [197, 219, 231]],

       ...,

       [[109, 127, 144],
        [120, 138, 155],
        [135, 151, 168],
        ...,
        [158, 168, 178],
        [163, 175, 187],
        [165, 179, 191]],

       [[114, 132, 149],
        [124, 142, 159],
        [138, 154, 171],
        ...,
        [ 91, 101, 111],
        [117, 130, 144],
        [158, 174, 187]],

       [[118, 136, 153],
        [123, 141, 158],
        [135, 151, 168],
        ...,
        [ 51,  61,  71],
        [ 40,  53,  67],
        [ 82,  98, 111]]

In [17]:
def read_data(label2id):
    X = []  # List to store image data
    Y = []  # List to store labels
    
    # Loop through the subdirectories in the 'Dog-Data/train' directory
    for label in os.listdir('../SVM-Classifier/Dog-Data/train'):
        # Check if the item in 'Dog-Data/train' is a directory
        if os.path.isdir(os.path.join('../SVM-Classifier/Dog-Data/train', label)):
            # Loop through image files in the current subdirectory
            for img_file in os.listdir(os.path.join('../SVM-Classifier/Dog-Data/train', label)):
                # Read the image using OpenCV's imread function
                img = cv2.imread(os.path.join('../SVM-Classifier/Dog-Data/train', label, img_file))
                
                # Append the image data to the X list
                X.append(img)
                
                # Use the label2id dictionary to map the label to an ID and append to Y list
                Y.append(label2id[label])
    
    # Return the lists of image data and labels
    return X, Y

In [18]:
tete_X = cv2.imread('../../../../../../Downloads/tete.jpg')

In [19]:
ex_X = cv2.imread('../SVM-Classifier/Dog-Data/train/0/cut_20201001_153748-0.jpg')

In [28]:
extract_sift_features(ex_X)

In [21]:
X, Y =  read_data(label2id)

In [22]:
len(X)

400

In [24]:
len(ex_X)

291

In [25]:
len(tete_X)

99

In [23]:
len(Y)

400

In [2]:
import os
import numpy as np
import cv2

import pickle
import sklearn
import argparse
import time

from sklearn.cluster import KMeans
from scipy.spatial.distance import cdist
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from histo_clahe import histo_clahe

# parser = argparse.ArgumentParser(description='Argparse Tutorial')
# parser.add_argument('--dir', default='Dog-Data',help='dataset directory')
# parser.add_argument('--test', default='test_1.jpg',help='test image data')
# opt = parser.parse_args()

#read data
def read_data(label2id):
    X = []  # List to store image data
    Y = []  # List to store labels
    
    # Loop through the subdirectories in the 'Dog-Data/train' directory
    for label in os.listdir('C:/Users/Playdata/Desktop/Save-Pets-ML-main/SVM-Classifier/Dog-Data/train'):
        # Check if the item in 'Dog-Data/train' is a directory
        if os.path.isdir(os.path.join('C:/Users/Playdata/Desktop/Save-Pets-ML-main/SVM-Classifier/Dog-Data/train', label)):
            # Loop through image files in the current subdirectory
            for img_file in os.listdir(os.path.join('C:/Users/Playdata/Desktop/Save-Pets-ML-main/SVM-Classifier/Dog-Data/train', label)):
                # Read the image using OpenCV's imread function
                img = cv2.imread(os.path.join('C:/Users/Playdata/Desktop/Save-Pets-ML-main/SVM-Classifier/Dog-Data/train', label, img_file))
                
                # Append the image data to the X list
                X.append(img)
                
                # Use the label2id dictionary to map the label to an ID and append to Y list
                Y.append(label2id[label])
    
    # Return the lists of image data and labels
    return X, Y


# feature exraction with SIFT
def extract_sift_features(X):
    image_descriptors = []  # List to store SIFT descriptors for each image
    
    '''
    A SIFT (Scale-Invariant Feature Transform) descriptor is a vector 
    that encodes information about the local appearance and orientation
    of a keypoint in an image. 
    It summarizes the distribution of gradient directions 
    around the keypoint, making it robust to changes 
    in scale, rotation, and lighting conditions. 
    Each SIFT descriptor is computed for a specific keypoint 
    and is used to represent that keypoint's local image region.
    '''
    
    # Create a SIFT object with specific parameters
    sift = cv2.xfeatures2d.SIFT_create(nfeatures=200, nOctaveLayers=3, contrastThreshold=0.0005)

    # Loop through the input images
    for i in range(len(X)):
        # Detect keypoints and compute descriptors using the SIFT object
        kp, des = sift.detectAndCompute(X[i], None)
        
        # Append the computed descriptors to the list of image_descriptors
        image_descriptors.append(des)

    # Return the list of SIFT descriptors for each image
    return image_descriptors


# Kmeans bow
def kmeans_bow(all_descriptors, num_clusters):
    bow_dict = []  # List to store cluster centers (visual words)
    
    # Perform K-means clustering on all SIFT descriptors to create the visual vocabulary
    kmeans = KMeans(n_clusters=num_clusters).fit(all_descriptors)
    
    # Get the cluster centers (visual words) from the K-means model
    bow_dict = kmeans.cluster_centers_
    
    return bow_dict


#image to vector.
def create_features_bow(image_descriptors, BoW, num_clusters):
    X_features = []  # List to store BoW features for each image
                     # BoW :  Bag of visual words (cluster centers obtained from K-means)
    
    for i in range(len(image_descriptors)):
        features = np.array([0] * num_clusters)  # Initialize a feature vector
        
        if image_descriptors[i] is not None:
            distance = cdist(image_descriptors[i], BoW)  # Compute distances to visual words
            argmin = np.argmin(distance, axis=1)  # Get the nearest visual word index for each descriptor
            
            # Count the occurrences of each visual word in the image
            for j in argmin:
                features[j] += 1
        
        X_features.append(features)  # Append the feature vector for the image
        
    return X_features

In [26]:
image_descriptors = extract_sift_features(X)

In [27]:
image_descriptors

[array([[ 23.,  18.,   9., ...,  40.,  30.,  38.],
        [  9.,   4.,  10., ..., 113.,  18.,   5.],
        [ 10.,  18.,  24., ...,   5.,   4.,   0.],
        ...,
        [  0.,   0.,  10., ...,   4.,   4.,  16.],
        [  0.,   1.,  15., ...,  16.,   6.,   3.],
        [  0.,   3.,  55., ...,  22.,  28.,  29.]], dtype=float32),
 array([[22., 15.,  7., ..., 14., 19., 40.],
        [ 7., 13., 31., ..., 16., 21., 29.],
        [65., 40.,  9., ...,  3.,  0., 17.],
        ...,
        [ 4., 26., 58., ...,  9., 33., 33.],
        [ 4.,  3.,  8., ..., 19., 27., 31.],
        [20., 16., 37., ...,  7., 33., 66.]], dtype=float32),
 array([[ 30.,  61.,  24., ...,   2.,  10.,  32.],
        [ 45.,   1.,   0., ...,  11.,  12.,  12.],
        [ 37.,  53.,  28., ...,  23.,   9.,  35.],
        ...,
        [116.,  26.,   0., ...,  51.,  92.,  29.],
        [ 27.,  10.,   4., ...,  30.,  19.,  27.],
        [ 20.,  21.,  43., ...,   1.,  65., 100.]], dtype=float32),
 array([[  3.,  29.,  62., .

In [16]:
all_descriptors = []
for descriptors in image_descriptors:
    if descriptors is not None:
        for des in descriptors:
            all_descriptors.append(des)

In [17]:
num_clusters = 100

In [18]:
BoW = pickle.load(open('C:/Users/Playdata/Desktop/Save-Pets-ML-main/SVM-Classifier/Dog-Data/bow.pkl', 'rb'))
X_features = create_features_bow(image_descriptors, BoW, num_clusters)


In [19]:
X_train = [] 
X_test = []
Y_train = []
Y_test = []
X_train, X_test, Y_train, Y_test = train_test_split(X_features, Y, test_size=0.2, random_state=42, shuffle=True)

In [20]:
svm = sklearn.svm.SVC(C = 100, probability=True)
svm.fit(X_train, Y_train)

SVC(C=100, probability=True)

In [21]:
knn = KNeighborsClassifier(n_neighbors=10,  weights='distance', leaf_size=200, p=2)
knn.fit(X_train, Y_train)

KNeighborsClassifier(leaf_size=200, n_neighbors=10, weights='distance')

In [22]:
img_test = histo_clahe('C:/Users/Playdata/Desktop/Save-Pets-ML-main/SVM-Classifier/Dog-Data/test/' + 'test_1.jpg')
img = [img_test]
img_sift_feature = extract_sift_features(img)
img_bow_feature = create_features_bow(img_sift_feature, BoW, num_clusters)

In [23]:
#predict SVM
img_predict = svm.predict(img_bow_feature)
#predict KNN
img_predict2 = knn.predict(img_bow_feature)

In [24]:
svm_prob = svm.predict_proba(img_bow_feature)[0][img_predict[0]]
knn_prob = knn.predict_proba(img_bow_feature)[0][img_predict2[0]]

In [39]:
svm.predict_proba(img_bow_feature)[0][img_predict[0]]

0.9701137560926586

In [25]:
svm_prob

0.9701137560926586

In [32]:
knn_prob

0.8769042330834412

In [27]:
img_predict

array([1])

In [29]:
for key, value in label2id.items():
    if value == img_predict[0]:
        svm_k = key
    if value == img_predict2[0]:
        knn_k = key

In [30]:
svm_k

'1'

In [31]:
knn_k

'1'

In [40]:
result =""
if svm_k==knn_k:
    result = result+svm_k+","
else:
    result = result+"a,"

In [41]:
result

'1,'

In [43]:
for key, value in label2id.items():
    print("key", key)
    print("value", value)

key 0
value 0
key 1
value 1
key 2
value 2
key 3
value 3
key 4
value 4
key 5
value 5
